version: "3"
services:
  server:
    image: app
    ports:
      - "8010:8010"
    build: ./back
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cinema?createDatabaseIfNotExist=true
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=cinema
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  front:
     image : frontapp
     build: ./front
     restart : always
     ports:
      - "4200:4200"
      

networks:
  springmysql-net:
